### ISSUE TITLE
Chat snaps to other user

### ISSUE THREAD

**Issue by SimonPlanje** [Vuurvos1/projectTechGroup#22]
When I send a message in a certain chat, the chat snaps to another user. The chat needs to stay at the same user when sending messages. See the bug for yourself at the /chat route after logging in.

**Comment by Vuurvos1** [comment]
Snapping is fixed, different chat bug where messages aren't properly received. Will start work on that now

**Comment by Vuurvos1** [comment]
Should be fixed now :)
